### ISSUE TITLE
how install in Atom?

### ISSUE THREAD

**Issue by cherniavsky94w** [xtoolkit/arshen-ac#3]

**Comment by xtoolkit** [comment]
hi
you can search 'arshen-ac' in search box atom package manager and install...
![untitled-2](https://user-images.githubusercontent.com/8210666/31968611-8e1ceec8-b91e-11e7-89f7-205266c9e80e.jpg)

**Comment by xtoolkit** [comment]
hi
you can serach 'arshen-ac' in install package and install package.
![untitled-2](https://user-images.githubusercontent.com/8210666/31968687-c987f61a-b91e-11e7-8859-400a96a0a467.jpg)
thank you

**Comment by cherniavsky94w** [comment]
thanks!
